[package]
name = "sidelb"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.45.0", features = ["net", "sync", "rt", "macros", "fs"] }
chrono = "0.4.41"
trust-dns-resolver = "0.23.2"

[profile.release]
lto = "thin"
debug = 0
opt-level = "z"
panic = "abort"
